<?php

namespace Database\Seeders;

use App\Models\Author;
use App\Models\Country;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        Country::query()->insert(array_map(
            fn ($item) => [
                'name' => $item[0],
                'code' => $item[1],
                'created_at' => '2023-01-01 00:00:00',
                'updated_at' => '2023-01-01 00:00:00',
            ],
            [
                ['Afghanistan', '+93'],
                ['Alaska', '+1907'],
                ['Albania', '+355'],
                ['Algeria', '+213'],
                ['American Samoa', '+684'],
                ['Andorra', '+376'],
                ['Angola', '+244'],
                ['Anguilla', '+1264'],
                ['Antigua', '+1268'],
                ['Argentina', '+54'],
                ['Armenia', '+374'],
                ['Aruba', '+297'],
                ['Ascention Island', '+247'],
                ['Australia', '+61'],
                ['Austria', '+43'],
                ['Azerbaijan', '+994'],
                ['Azores', '+351'],
                ['Bahamas', '+1242'],
                ['Bahrain', '+973'],
                ['Bangladesh', '+880'],
                ['Barbados', '+1246'],
                ['Belarus', '+375'],
                ['Belgium', '+32'],
                ['Belize', '+501'],
                ['Benin', '+229'],
                ['Bermuda', '+1441'],
                ['Bhutan', '+975'],
                ['Bosnia and Herzegovina', '+387'],
                ['Botswana', '+267'],
                ['Brazil', '+55'],
                ['Brunei Darussalam', '+673'],
                ['Bulgaria', '+359'],
                ['Burkina Faso', '+226'],
                ['Burundi', '+257'],
                ['Cameroon', '+237'],
                ['Canada', '+1'],
                ['Canary Island', '+34'],
                ['Cape Verde', '+238'],
                ['Cayman Islands', '+1345'],
                ['Central African Republic', '+236'],
                ['Chad', '+235'],
                ['Chile', '+56'],
                ['China', '+86'],
                ['Christmas Island', '+61'],
                ['Ciskei', '+27'],
                ['Colombia', '+57'],
                ['Comoros', '+269'],
                ['Congo', '+242'],
                ['Costa Rica', '+506'],
                ['Croatia (Hrvatska)', '+385'],
                ['Cuba', '+53'],
                ['Cyprus', '+357'],
                ['Czech Republic', '+420'],
                ['Denmark', '+45'],
                ['Diego Garcia', '+246'],
                ['Djibouti', '+253'],
                ['Dominican Republic', '+1'],
                ['East Timor', '+670'],
                ['Ecuador', '+593'],
                ['Egypt', '+20'],
                ['El Salvador', '+503'],
                ['Eritrea', '+291'],
                ['Estonia', '+372'],
                ['Ethiopia', '+251'],
                ['Falkland Island', '+500'],
                ['Faroe Island', '+298'],
                ['Fiji Islands', '+679'],
                ['Finland', '+358'],
                ['France', '+33'],
                ['Gabon', '+241'],
                ['Gambia', '+220'],
                ['Georgia', '+995'],
                ['Germany', '+49'],
                ['Ghana', '+233'],
                ['Gibraltar', '+350'],
                ['Greece', '+30'],
                ['Greenland', '+299'],
                ['Guadelope', '+590'],
                ['Guam', '+1671'],
                ['Guatemala', '+502'],
                ['Guinea', '+224'],
                ['Guinea Bissau', '+245'],
                ['Guyana', '+592'],
                ['Haiti', '+509'],
                ['Honduras', '+504'],
                ['Hong Kong', '+852'],
                ['Hungary', '+36'],
                ['Iceland', '+354'],
                ['India', '+91'],
                ['Indonesia', '+62'],
                ['Iran', '+98'],
                ['Iraq', '+964'],
                ['Ireland', '+353'],
                ['Israel', '+972'],
                ['Italy', '+39'],
                ['Ivory Coast', '+225'],
                ['Jamaica', '+1876'],
                ['Japan', '+81'],
                ['Jordan', '+962'],
                ['Kampuchea', '+855'],
                ['Kazakhstan', '+731'],
                ['Kazakhstan', '+7'],
                ['Kenya', '+254'],
                ['Kiribati', '+686'],
                ['Korea (North)', '+850'],
                ['Korea (South)', '+82'],
                ['Kuwait', '+965'],
                ['Kyrgyzstan', '+996'],
                ['Laos', '+856'],
                ['Latvia', '+371'],
                ['Lebanon', '+961'],
                ['Lesotho', '+266'],
                ['Liberia', '+231'],
                ['Libya', '+218'],
                ['Lithuania', '+370'],
                ['Luxembourg', '+352'],
                ['Macau', '+853'],
                ['Macedonia', '+389'],
                ['Madagascar', '+261'],
                ['Madeira Island', '+351'],
                ['Malawi', '+265'],
                ['Malaysia', '+60'],
                ['Maldives', '+960'],
                ['Mali', '+223'],
                ['Malta', '+356'],
                ['Marshall Island', '+692'],
                ['Mauritania', '+222'],
                ['Mauritius', '+230'],
                ['Mexico', '+52'],
                ['Monaco', '+377'],
                ['Mongolia', '+976'],
                ['Morocco', '+212'],
                ['Mozambique', '+258'],
                ['Myanmar', '+95'],
                ['Namibia', '+264'],
                ['Nauru', '+674'],
                ['Nepal', '+977'],
                ['Netherlands', '+31'],
                ['Netherlands Antilles', '+599'],
                ['New Zealand', '+64'],
                ['Nicaragua', '+505'],
                ['Niger', '+227'],
                ['Nigeria', '+234'],
                ['Norfolk Island', '+672'],
                ['Norway', '+47'],
                ['Oman', '+968'],
                ['Pakistan', '+92'],
                ['Palau', '+680'],
                ['Palestine', '+970'],
                ['Panama', '+507'],
                ['Papua New Guinea', '+675'],
                ['Papua New Guinea', '+675'],
                ['Paraguay', '+595'],
                ['Peru', '+51'],
                ['Philippines', '+63'],
                ['Poland', '+48'],
                ['Portugal', '+351'],
                ['Puerto Rico', '+1787'],
                ['Qatar', '+974'],
                ['Romania', '+40'],
                ['Russia', '+7'],
                ['Rwanda', '+250'],
                ['Samoa', '+685'],
                ['San Marino', '+378'],
                ['Sao Tome', '+239'],
                ['Saudi Arabia', '+966'],
                ['Senegal', '+221'],
                ['Serbia & Montenegro', '+381'],
                ['Seychelles', '+248'],
                ['Sierra Leone', '+232'],
                ['Singapore', '+65'],
                ['Slovak Republic', '+421'],
                ['Slovakia', '+421'],
                ['Slovenia', '+386'],
                ['Solomon Islands', '+677'],
                ['Somalia', '+252'],
                ['South Africa', '+27'],
                ['Spain', '+34'],
                ['Sri Lanka', '+94'],
                ['St. Kitts & Navis', '+1869'],
                ['St. Vincent & Grenadian', '+1784'],
                ['Sudan', '+249'],
                ['Suriname', '+597'],
                ['Swaziland', '+268'],
                ['Sweden', '+46'],
                ['Switzerland', '+41'],
                ['Syria', '+963'],
                ['Taiwan', '+886'],
                ['Tajikistan', '+992'],
                ['Tanzania', '+255'],
                ['Thailand', '+66'],
                ['Togo', '+228'],
                ['Tonga', '+676'],
                ['Trinidad and Tobago', '+1868'],
                ['Tunisia', '+216'],
                ['Turkey', '+90'],
                ['Turkmenistan', '+7370'],
                ['Tuvalu', '+688'],
                ['Uganda', '+256'],
                ['Ukraine', '+380'],
                ['United Arab Emirates', '+971'],
                ['United Kingdom (UK)', '+44'],
                ['Uruguay', '+598'],
                ['USA', '+1'],
                ['Uzbekistan', '+998'],
                ['Vanatu', '+678'],
                ['Vatican City State (Holy See)', '+379'],
                ['Venezuela', '+58'],
                ['Vietnam', '+84'],
                ['Virgin Island', '+1340'],
                ['Western Sahara', '+212'],
                ['Yemen', '+967'],
                ['Yugoslavia', '+381'],
                ['Zaire', '+243'],
                ['Zambia', '+260'],
                ['Zimbabwe', '+263'],
                ['Montenegro', '+382'],
            ]
        ));

        Permission::query()->insert(array_map(
            fn ($permission) => [
                'name' => $permission,
                'guard_name' => 'web',
                'created_at' => '2023-01-01 00:00:00',
                'updated_at' => '2023-01-01 00:00:00',
            ],
            Permission::getConstants()
        ));

        $permissions = Permission::all();

        Role::query()->insert(array_map(
            fn ($item) => [
                'name' => $item[0],
                'guard_name' => 'web',
                'section' => $item[1],
                'default' => $item[2],
                'created_at' => '2023-01-01 00:00:00',
                'updated_at' => '2023-01-01 00:00:00',
            ],
            [
                ['Admin', 'admin', 0],
                ['Author', 'author', 1],
                ['Reviewer', 'reviewer', 1],
                ['Associate Editor', 'associate-editor', 0],
                ['Editor In Chief', 'editor-in-chief', 0],
                ['EPM', 'epm', 0]
            ]
        ));

        $roles = Role::all();

        $roles->each(
            fn ($role) => $role->permissions()->sync($permissions)
        );

        $user = Author::create([
            'title' => 'Mr.',
            'first_name' => 'Ajay',
            'last_name' => 'Nautiyal',
            'email' => 'aju@nautiyal.dev',
            'password' => bcrypt('Secret$123456'),
            'country_id' => 89,
            'email_verified_at' => '2023-01-01 00:00:00',
            'created_at' => '2023-01-01 00:00:00',
            'updated_at' => '2023-01-01 00:00:00',
        ]);

        $user->roles()->sync($roles);
    }
}
